#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
THEMES_DIR="$ROOT/repos/themes/colorschemes"
TOOLS_DIR="$ROOT/repos/tools"
GUI_APPS_DIR="$ROOT/repos/themes/gui-apps"
CURATED_DIR="$ROOT/repos/curated"
RELATED_DIR="$ROOT/repos/related"

OK=0
SKIP=0
FAIL=0

clone() {
  local url="$1"
  local dest="$2"
  if [[ -d "$dest/.git" ]]; then
    echo "  skip  $dest"
    ((SKIP++)) || true
    return
  fi
  if git clone --depth 1 "$url" "$dest" 2>/dev/null; then
    echo "  clone $dest"
    ((OK++)) || true
  else
    echo "  FAIL  $url -> $dest"
    ((FAIL++)) || true
  fi
}

mkdir -p "$THEMES_DIR" "$TOOLS_DIR" "$GUI_APPS_DIR" "$CURATED_DIR" "$RELATED_DIR"

echo "=== Themes ==="
clone https://github.com/vyrx-dev/omarchy-aamis-theme         "$THEMES_DIR/omarchy-aamis-theme"
clone https://github.com/grierson/omarchy-alabaster-theme      "$THEMES_DIR/omarchy-alabaster-theme"
clone https://github.com/rblalock/omarchy-agentuity.theme      "$THEMES_DIR/omarchy-agentuity-theme"
clone https://github.com/guilhermetk/omarchy-all-hallows-eve-theme "$THEMES_DIR/omarchy-all-hallows-eve-theme"
clone https://github.com/tahfizhabib/omarchy-amberbyte-theme   "$THEMES_DIR/omarchy-amberbyte-theme"
clone https://github.com/fdidron/omarchy-ayumirage             "$THEMES_DIR/omarchy-ayumirage"
clone https://github.com/abhijeet-swami/omarchy-ayaka-theme    "$THEMES_DIR/omarchy-ayaka-theme"
clone https://github.com/Hydradevx/omarchy-azure-glow-theme    "$THEMES_DIR/omarchy-azure-glow-theme"
clone https://github.com/somerocketeer/omarchy-bauhaus-theme   "$THEMES_DIR/omarchy-bauhaus-theme"
clone https://github.com/HANCORE-linux/omarchy-blackmoney-theme "$THEMES_DIR/omarchy-blackmoney-theme"
clone https://github.com/hipsterusername/omarchy-blueridge-dark-theme "$THEMES_DIR/omarchy-blueridge-dark-theme"
clone https://github.com/hoblin/omarchy-cobalt2-theme          "$THEMES_DIR/omarchy-cobalt2-theme"
clone https://github.com/knappkevin/omarchy-crimson-gold-theme "$THEMES_DIR/omarchy-crimson-gold-theme"
clone https://github.com/AX200M/omarchy-doom-theme             "$THEMES_DIR/omarchy-doom-theme"
clone https://github.com/catlee/omarchy-dracula-theme          "$THEMES_DIR/omarchy-dracula-theme"
clone https://github.com/jbnunn/omarchy-delorean-theme         "$THEMES_DIR/omarchy-delorean-theme"
clone https://github.com/Hydradevx/omarchy-ember-n-ash-theme   "$THEMES_DIR/omarchy-ember-n-ash-theme"
clone https://github.com/bjarneo/omarchy-elysian-theme         "$THEMES_DIR/omarchy-elysian-theme"
clone https://github.com/Swarnim114/omarchy-everblush-theme    "$THEMES_DIR/omarchy-everblush-theme"
clone https://github.com/celsobenedetti/omarchy-evergarden      "$THEMES_DIR/omarchy-evergarden"
clone https://github.com/TyRichards/omarchy-felix-theme        "$THEMES_DIR/omarchy-felix-theme"
clone https://github.com/bjarneo/omarchy-fiery-ocean-theme     "$THEMES_DIR/omarchy-fiery-ocean-theme"
clone https://github.com/euandeas/omarchy-flexoki-dark-theme   "$THEMES_DIR/omarchy-flexoki-dark-theme"
clone https://github.com/euandeas/omarchy-flexoki-light-theme  "$THEMES_DIR/omarchy-flexoki-light-theme"
clone https://github.com/abhijeet-swami/omarchy-forest-green-theme "$THEMES_DIR/omarchy-forest-green-theme"
clone https://github.com/tahayvr/omarchy-gold-rush-theme       "$THEMES_DIR/omarchy-gold-rush-theme"
clone https://github.com/bjarneo/omarchy-gtk-theme             "$THEMES_DIR/omarchy-gtk-theme"
clone https://github.com/kalk-ak/omarchy-green-garden-theme    "$THEMES_DIR/omarchy-green-garden-theme"
clone https://github.com/HANCORE-linux/omarchy-harbor-theme    "$THEMES_DIR/omarchy-harbor-theme"
clone https://github.com/HANCORE-linux/omarchy-harbordark-theme "$THEMES_DIR/omarchy-harbordark-theme"
clone https://github.com/bjarneo/omarchy-hollow-knight-theme   "$THEMES_DIR/omarchy-hollow-knight-theme"
clone https://github.com/imbypass/omarchy-hook-theme-set-ex    "$THEMES_DIR/omarchy-hook-theme-set-ex"
clone https://github.com/HANCORE-linux/omarchy-inkypinky-theme "$THEMES_DIR/omarchy-inkypinky-theme"
clone https://github.com/krymzonn/omarchy-kimiko-theme         "$THEMES_DIR/omarchy-kimiko-theme"
clone https://github.com/steve-lohmeyer/omarchy-mars-theme     "$THEMES_DIR/omarchy-mars-theme"
clone https://github.com/HANCORE-linux/omarchy-mechanoonna-theme "$THEMES_DIR/omarchy-mechanoonna-theme"
clone https://github.com/tahayvr/omarchy-matte-black           "$THEMES_DIR/omarchy-matte-black"
clone https://github.com/hipsterusername/omarchy-milkmatcha-light-theme "$THEMES_DIR/omarchy-milkmatcha-light-theme"
clone https://github.com/Swarnim114/omarchy-monochrome-theme   "$THEMES_DIR/omarchy-monochrome-theme"
clone https://github.com/HANCORE-linux/omarchy-moodpeak-theme  "$THEMES_DIR/omarchy-moodpeak-theme"
clone https://github.com/somerocketeer/omarchy-nagai-twilight-theme "$THEMES_DIR/omarchy-nagai-twilight-theme"
clone https://github.com/Justikun/omarchy-osaka-jade-theme     "$THEMES_DIR/omarchy-osaka-jade-theme"
clone https://github.com/dotsilva/omarchy-purplewave-theme     "$THEMES_DIR/omarchy-purplewave-theme"
clone https://github.com/guilhermetk/omarchy-rose-pine-dark    "$THEMES_DIR/omarchy-rose-pine-dark"
clone https://github.com/bjarneo/omarchy-serenity-theme        "$THEMES_DIR/omarchy-serenity-theme"
clone https://github.com/HANCORE-linux/omarchy-shadesofjade-theme "$THEMES_DIR/omarchy-shadesofjade-theme"
clone https://github.com/bjarneo/omarchy-snow-theme            "$THEMES_DIR/omarchy-snow-theme"
clone https://github.com/dfrico/omarchy-solarized-light-theme  "$THEMES_DIR/omarchy-solarized-light-theme"
clone https://github.com/motorsss/omarchy-solarizedosaka-theme "$THEMES_DIR/omarchy-solarizedosaka-theme"
clone https://github.com/Gazler/omarchy-solarized-theme        "$THEMES_DIR/omarchy-solarized-theme"
clone https://github.com/TyRichards/omarchy-space-monkey-theme "$THEMES_DIR/omarchy-space-monkey-theme"
clone https://github.com/abhijeet-swami/omarchy-spectra-theme  "$THEMES_DIR/omarchy-spectra-theme"
clone https://github.com/tahayvr/omarchy-sunset-drive-theme    "$THEMES_DIR/omarchy-sunset-drive-theme"
clone https://github.com/omacom-io/omarchy-synthwave84-theme   "$THEMES_DIR/omarchy-synthwave84-theme"
clone https://github.com/HANCORE-linux/omarchy-thegreek-theme  "$THEMES_DIR/omarchy-thegreek-theme"
clone https://github.com/perfektnacht/omarchy-velocity-theme   "$THEMES_DIR/omarchy-velocity-theme"
clone https://github.com/HANCORE-linux/omarchy-velvetnight-theme "$THEMES_DIR/omarchy-velvetnight-theme"
clone https://github.com/thmoee/omarchy-vesper-theme           "$THEMES_DIR/omarchy-vesper-theme"
clone https://github.com/tahayvr/omarchy-vhs80-theme           "$THEMES_DIR/omarchy-vhs80-theme"
clone https://github.com/vyrx-dev/omarchy-void-theme           "$THEMES_DIR/omarchy-void-theme"
clone https://github.com/perfektnacht/omarchy-wasteland-theme  "$THEMES_DIR/omarchy-wasteland-theme"
clone https://github.com/HANCORE-linux/omarchy-whitegold-theme "$THEMES_DIR/omarchy-whitegold-theme"
clone https://github.com/hipsterusername/omarchy-waveform-dark-theme "$THEMES_DIR/omarchy-waveform-dark-theme"
clone https://github.com/rondilley/omarchy-motivator-theme     "$THEMES_DIR/omarchy-motivator-theme"
clone https://github.com/CyphrRiot/omarchy-archriot-theme      "$THEMES_DIR/omarchy-archriot-theme"
clone https://github.com/vale-c/omarchy-arc-blueberry          "$THEMES_DIR/omarchy-arc-blueberry"
clone https://github.com/fdidron/omarchy-ayu-dark-theme        "$THEMES_DIR/omarchy-ayu-dark-theme"
clone https://github.com/fdidron/omarchy-ayu-light-theme       "$THEMES_DIR/omarchy-ayu-light-theme"
clone https://github.com/ryanyogan/omarchy-github-light-theme  "$THEMES_DIR/omarchy-github-light-theme"
clone https://github.com/maxberggren/omarchy-night-owl-theme   "$THEMES_DIR/omarchy-night-owl-theme"
clone https://github.com/KidDogDad/omarchy-catppuccin-mocha-theme "$THEMES_DIR/omarchy-catppuccin-mocha-theme"
clone https://github.com/MrTrigger/omarchy-kanagawa-dragon-theme "$THEMES_DIR/omarchy-kanagawa-dragon-theme"
clone https://github.com/ericrswanny/omarchy-monokai-dark-theme "$THEMES_DIR/omarchy-monokai-dark-theme"
clone https://github.com/Hydradevx/omarchy-obsidian-theme      "$THEMES_DIR/omarchy-obsidian-theme"
clone https://github.com/ryanyogan/omarchy-rose-pine-dawn-theme "$THEMES_DIR/omarchy-rose-pine-dawn-theme"
clone https://github.com/guilhermetk/omarchy-rose-pine         "$THEMES_DIR/omarchy-rose-pine"
clone https://github.com/j4v3l/omarchy-anonymous-theme         "$THEMES_DIR/omarchy-anonymous-theme"
clone https://github.com/bjarneo/omarchy-wood-theme            "$THEMES_DIR/omarchy-wood-theme"
clone https://github.com/bjarneo/omarchy-pina-theme            "$THEMES_DIR/omarchy-pina-theme"
clone https://github.com/ITSZXY/pink-blood-omarchy-theme       "$THEMES_DIR/pink-blood-omarchy-theme"
clone https://github.com/bjarneo/omarchy-reverie-theme         "$THEMES_DIR/omarchy-reverie-theme"
clone https://github.com/HANCORE-linux/omarchy-sapphire-theme  "$THEMES_DIR/omarchy-sapphire-theme"
clone https://github.com/bjarneo/omarchy-fireside-theme        "$THEMES_DIR/omarchy-fireside-theme"
clone https://github.com/bjarneo/omarchy-frost-theme           "$THEMES_DIR/omarchy-frost-theme"
clone https://github.com/daurydicaprio/omarchy-pure-latin-theme "$THEMES_DIR/omarchy-pure-latin-theme"
clone https://github.com/leonardobetti/omarchy-tycho           "$THEMES_DIR/omarchy-tycho"
clone https://github.com/scar45/omarchy-c64-theme              "$THEMES_DIR/omarchy-c64-theme"
clone https://github.com/999Gabriel/F1-omarchy                 "$THEMES_DIR/F1-omarchy"
clone https://github.com/dracula/omarchy                       "$THEMES_DIR/dracula-omarchy"
clone https://github.com/JJDizz1L/aetheria                    "$THEMES_DIR/aetheria"

echo ""
echo "=== Alternative Implementations ==="
clone https://github.com/hinriksnaer/Fedpunk                   "$CURATED_DIR/Fedpunk"
clone https://github.com/elpritchos/omadora                    "$CURATED_DIR/omadora"
clone https://github.com/lentra0/omarchy-cachyos               "$CURATED_DIR/omarchy-cachyos"
clone https://github.com/henrysipp/omarchy-nix                 "$CURATED_DIR/omarchy-nix"
clone https://github.com/mroboff/omarchy-on-cachyos            "$CURATED_DIR/omarchy-on-cachyos"
clone https://github.com/ChrisTitusTech/omarchy-titus          "$CURATED_DIR/omarchy-titus"
clone https://github.com/typecraft-dev/omarchy-supplement      "$CURATED_DIR/omarchy-supplement"
clone https://github.com/harilvfs/omarchy                      "$CURATED_DIR/harilvfs-omarchy"
clone https://github.com/Alexx2/omarchy-themes                 "$CURATED_DIR/Alexx2-omarchy-themes"

echo ""
echo "=== Development Tools ==="
clone https://github.com/rhemvi/omaclip                        "$TOOLS_DIR/omaclip"
clone https://github.com/mitkox/omarchy-ai                     "$TOOLS_DIR/omarchy-ai"
clone https://github.com/omacom-io/omarchy-iso                 "$TOOLS_DIR/omarchy-iso"
clone https://github.com/dylanbr/omarchy-box                   "$TOOLS_DIR/omarchy-box"
clone https://github.com/omacom-io/omarchy-chromium            "$TOOLS_DIR/omarchy-chromium"
clone https://github.com/omacom-io/omarchy-configurator        "$TOOLS_DIR/omarchy-configurator"
clone https://github.com/omacom-io/omarchy-installer           "$TOOLS_DIR/omarchy-installer"
clone https://github.com/hipsterusername/omarchy-themes-generator "$TOOLS_DIR/omarchy-themes-generator"
clone https://github.com/maxberggren/omarchy-theme-generator   "$TOOLS_DIR/omarchy-theme-generator"
clone https://github.com/joaofelipegalvao/omarchy-tmux         "$TOOLS_DIR/omarchy-tmux-galvao"
clone https://github.com/CyphrRiot/Migrate                     "$TOOLS_DIR/omarchy-migrate"
clone https://github.com/HectorBjernersjo/Neovim-theme-switcher "$TOOLS_DIR/Neovim-theme-switcher"
clone https://github.com/thatmechguy/omarchy-material-waybar   "$TOOLS_DIR/omarchy-material-waybar"
clone https://github.com/ryanyogan/omarchy-monitor-settings    "$TOOLS_DIR/omarchy-monitor-settings"
clone https://github.com/Firstp1ck/Pacsea                      "$TOOLS_DIR/Pacsea"
clone https://github.com/timmo001/omarchy-waybar               "$TOOLS_DIR/omarchy-waybar"
clone https://github.com/HANCORE-linux/waybar-themes           "$TOOLS_DIR/waybar-themes"
clone https://github.com/timmo001/omarchy-hypr                 "$TOOLS_DIR/omarchy-hypr"
clone https://github.com/hjanuschka/OMARCHY-VM-UTM             "$TOOLS_DIR/OMARCHY-VM-UTM"
clone https://github.com/jonashan/omarchy-workspace-mover      "$TOOLS_DIR/omarchy-workspace-mover"
clone https://github.com/JacobusXIII/omarchy-wireguard-vpn-toggle "$TOOLS_DIR/omarchy-wireguard-vpn-toggle"
clone https://github.com/APS6/omazed                           "$TOOLS_DIR/omazed"
clone https://github.com/aloisdeniel/flutter_omarchy           "$TOOLS_DIR/flutter_omarchy"
clone https://github.com/omacom-io/omarchy-pkgs               "$TOOLS_DIR/omarchy-pkgs"
clone https://github.com/acrogenesis/omarchy-cheat-sheet       "$TOOLS_DIR/omarchy-cheat-sheet"
clone https://github.com/jg-k/omarchy-theme-builder            "$TOOLS_DIR/omarchy-theme-builder-jgk"
clone https://github.com/gitcoder89431/omarchy-theme-builder    "$TOOLS_DIR/omarchy-theme-builder-gitcoder"
clone https://github.com/2disbetter/FW12Rotate                 "$TOOLS_DIR/FW12Rotate"
clone https://github.com/JaimeStill/omarchy-theme-generator    "$TOOLS_DIR/omarchy-theme-generator-jaime"
clone https://github.com/nemuiyarou/omarchy-enhanced-bindings  "$TOOLS_DIR/omarchy-enhanced-bindings"
clone https://github.com/adsovetzky/Adsovetzky-Omarchy-s-Waybar "$TOOLS_DIR/Adsovetzky-Omarchy-s-Waybar"
clone https://github.com/amanat361/omarchy-gui                 "$TOOLS_DIR/omarchy-gui"
clone https://github.com/devmobasa/hyprmarker                  "$TOOLS_DIR/hyprmarker"
clone https://github.com/t4t5/hypruler                         "$TOOLS_DIR/hypruler"
clone https://github.com/Grenish/clipboard-manager             "$TOOLS_DIR/clipboard-manager"
clone https://github.com/mirarr-app/editt                      "$TOOLS_DIR/editt"
clone https://github.com/michabbb/omarchy-speech-to-text       "$TOOLS_DIR/omarchy-speech-to-text"
clone https://github.com/cephalization/omarchy-steam-gaming-mode "$TOOLS_DIR/omarchy-steam-gaming-mode"
clone https://github.com/daurydicaprio/live-wallpaper-for-omarchy-linux "$TOOLS_DIR/live-wallpaper-for-omarchy-linux"
clone https://github.com/aloisdeniel/omarchy_calculator        "$TOOLS_DIR/omarchy-calculator"
clone https://github.com/daurydicaprio/manual-nas-backup-tool  "$TOOLS_DIR/manual-nas-backup-tool"
clone https://github.com/daurydicaprio/omarchy-monitor-toggle  "$TOOLS_DIR/omarchy-monitor-toggle"
clone https://github.com/magudb/hyprBluetooth                  "$TOOLS_DIR/hyprBluetooth"
clone https://github.com/tomycostantino/omarchpods             "$TOOLS_DIR/omarchpods"
clone https://github.com/blank-query/lazyVPN-for-Omarchy       "$TOOLS_DIR/lazyVPN-for-Omarchy"

echo ""
echo "=== Related Projects ==="
clone https://github.com/j5onrf/dots                           "$RELATED_DIR/j5onrf-dots"
clone https://github.com/dougburks/ohmydebn                   "$RELATED_DIR/ohmydebn"
clone https://github.com/alibaghernejad/waybar-privacy-dots    "$RELATED_DIR/waybar-privacy-dots"
clone https://github.com/omacom-io/omarchy-site               "$RELATED_DIR/omarchy-site"
clone https://github.com/omacom-io/omarchy-mirror             "$RELATED_DIR/omarchy-mirror"
clone https://github.com/marcelohmdias/dotfiles                "$RELATED_DIR/marcelohmdias-dotfiles"
clone https://github.com/pixincreate/configs                   "$RELATED_DIR/pixincreate-configs"
clone https://github.com/jehrhardt/dotfiles                    "$RELATED_DIR/jehrhardt-dotfiles"
clone https://github.com/sheikhlimon/dotfiles                  "$RELATED_DIR/sheikhlimon-dotfiles"
clone https://github.com/donotfeedthevirus/dotfiles            "$RELATED_DIR/donotfeedthevirus-dotfiles"

echo ""
echo "=== Summary ==="
echo "  cloned: $OK"
echo "  skipped (already present): $SKIP"
echo "  failed: $FAIL"
echo ""
echo "Disk usage after:"
du -sh "$ROOT/repos/"
