# Hight — Dynamic-style wind bezier, similar to dynamic but faster

animations {
  enabled = true

  bezier = wind, 0.17, 0.67, 0.29, 1.0
  bezier = winIn, 0.1, 0.8, 0.3, 1.0
  bezier = winOut, 0.3, 0.0, 0.8, 0.1

  animation = windows, 1, 6, winIn, slide
  animation = windowsOut, 1, 4, winOut, slide
  animation = fade, 1, 4, wind
  animation = workspaces, 1, 5, wind, slidevert
}
