#!/usr/bin/env bash
# Obsidian theme hook — generates CSS for Obsidian vaults from theme colors

THEME_NAME="${1:-unknown}"
THEME_DIR="${OMARCHY_THEME_DIR:-$HOME/.config/omarchy/themes/$THEME_NAME}"
STATE_DIR="${OMARCHY_STATE_DIR:-$HOME/.local/state/omarchy}"
VAULT_REGISTRY="$STATE_DIR/obsidian-vaults"

# Build vault registry from Obsidian config
OBSIDIAN_CONFIG="$HOME/.config/obsidian/obsidian.json"
mkdir -p "$STATE_DIR"
> "$VAULT_REGISTRY"

if [[ -f "$OBSIDIAN_CONFIG" ]]; then
    python3 -c "
import json, os
with open('$OBSIDIAN_CONFIG') as f:
    data = json.load(f)
vaults = data.get('vaults', {})
with open('$VAULT_REGISTRY', 'w') as out:
    for vid, vinfo in vaults.items():
        path = vinfo.get('path', '')
        if path:
            out.write(path + '\n')
" 2>/dev/null || true
fi

# Generate theme CSS for each vault
COLORS_FILE="$THEME_DIR/colors.toml"
[[ -f "$COLORS_FILE" ]] || exit 0

ALACRITTY_FILE="$THEME_DIR/alacritty.toml"
if [[ ! -f "$ALACRITTY_FILE" ]]; then
    ALACRITTY_FILE="$THEME_DIR/alacritty.toml"
fi

generate_obsidian_css() {
    cat <<'CSSHEADER'
/* Auto-generated by omarchy theme-hook */
:root {
CSSHEADER
    if [[ -f "$ALACRITTY_FILE" ]]; then
        grep -E '^\s*(background|foreground)\s*=' "$ALACRITTY_FILE" | \
            sed 's/background/--bg/;s/foreground/--fg/;s/"//g'
    fi
    echo "}"
}

while IFS= read -r vault_path; do
    [[ -z "$vault_path" ]] && continue
    OBSIDIAN_THEMES="$vault_path/.obsidian/themes/Omarchy"
    mkdir -p "$OBSIDIAN_THEMES"
    generate_obsidian_css > "$OBSIDIAN_THEMES/theme.css"
    cat > "$OBSIDIAN_THEMES/manifest.json" <<EOF
{"name": "Omarchy-$THEME_NAME", "version": "1.0.0", "minAppVersion": "1.0.0"}
EOF
    echo "Obsidian theme generated for: $vault_path"
done < "$VAULT_REGISTRY"
