#!/usr/bin/env bash
# GTK theme hook — applies OMARCHY theme to GTK apps
# Activated by removing .sample suffix (or sourcing from apply.sh)
# Receives theme name as $1

THEME_NAME="${1:-unknown}"
THEME_DIR="${OMARCHY_THEME_DIR:-$HOME/.config/omarchy/themes/$THEME_NAME}"

# Determine light/dark from theme
LIGHT_MODE_FILE="$THEME_DIR/light.mode"
if [[ -f "$LIGHT_MODE_FILE" ]]; then
    COLOR_SCHEME="prefer-light"
    GTK_THEME="Adwaita"
else
    COLOR_SCHEME="prefer-dark"
    GTK_THEME="Adwaita-dark"
fi

# GNOME settings
if command -v gsettings &>/dev/null; then
    gsettings set org.gnome.desktop.interface color-scheme "$COLOR_SCHEME"
    gsettings set org.gnome.desktop.interface gtk-theme "$GTK_THEME"
    # Apply icon theme from theme if available
    ICONS_FILE="$THEME_DIR/icons.theme"
    if [[ -f "$ICONS_FILE" ]]; then
        gsettings set org.gnome.desktop.interface icon-theme "$(cat "$ICONS_FILE")"
    fi
fi

# Generate GTK CSS from theme colors
COLS_FILE="$THEME_DIR/colors.toml"
GTK_CSS_DIR="$HOME/.config/gtk-3.0"
if [[ -f "$COLS_FILE" ]]; then
    mkdir -p "$GTK_CSS_DIR"
    cat > "$GTK_CSS_DIR/gtk.css" <<EOF
/* Auto-generated by omarchy theme-hook — $THEME_NAME */
$(grep -E '^@define-color' "$COLS_FILE" 2>/dev/null || echo "/* no colors defined */")

window, .background, .titlebar {
    background-color: @theme_bg_color;
    color: @theme_fg_color;
}
entry, button, .entry, .button {
    background-color: shade(@theme_bg_color, 1.2);
    color: @theme_fg_color;
    border-color: @theme_selected_bg_color;
}
EOF
fi

echo "GTK theme hook: $THEME_NAME ($COLOR_SCHEME)"
